@baseUrl = http://localhost:8000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "678ba67bcd342bb4eb0a8568",
  "receiverId": "678a8c47a3fec1f5ec01fe59",
  "receiverUsername": "Maria",
  "receiverAvatarColor": "pink",
  "receiverProfilePicture": "https://res.cloudinary.com/dahchezq8/image/upload/v1737065789/6789853d5216080dea094449",
  "body": "and you?",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "678816acb9559ff2e621e98f",
  "userTwo": "6789853d5216080dea094449"
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "678816acb9559ff2e621e98f",
  "userTwo": "6789853d5216080dea094449"
}

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/chat/message/user/678a8c47a3fec1f5ec01fe59
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE  {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/678ba6c6cd342bb4eb0a8572/678a8c24a3fec1f5ec01fe52/678a8c47a3fec1f5ec01fe59/deleteForMe
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT   {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "678a8c24a3fec1f5ec01fe52",
  "receiverId": "678a8c47a3fec1f5ec01fe59"
}
