@baseUrl = http://localhost:8000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "678a903a9910dad2485b45dd",
  "receiverId": "678a8c47a3fec1f5ec01fe59",
  "receiverUsername": "Maria",
  "receiverAvatarColor": "pink",
  "receiverProfilePicture": "https://res.cloudinary.com/dahchezq8/image/upload/v1737065789/6789853d5216080dea094449",
  "body": "I am well.",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "678816acb9559ff2e621e98f",
  "userTwo": "6789853d5216080dea094449"
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "678816acb9559ff2e621e98f",
  "userTwo": "6789853d5216080dea094449"
}

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true
